CREATE TABLE td_orders (
    id INT PRIMARY KEY,
    type VARCHAR(50),
    symbol VARCHAR(50),
    side VARCHAR(50),
    quantity FLOAT,
    status VARCHAR(50),
    duration VARCHAR(50),
    price FLOAT,
    avg_fill_price FLOAT,
    exec_quantity FLOAT,
    last_fill_price FLOAT,
    last_fill_quantity FLOAT,
    remaining_quantity FLOAT,
    create_date DATETIME,
    transaction_date DATETIME,
    class VARCHAR(50),
    num_legs INT,
    strategy VARCHAR(50)
);

CREATE TABLE td_legs (
    id INT PRIMARY KEY,
    order_id INT,
    type VARCHAR(50),
    symbol VARCHAR(50),
    side VARCHAR(50),
    quantity FLOAT,
    status VARCHAR(50),
    duration VARCHAR(50),
    price FLOAT,
    avg_fill_price FLOAT,
    exec_quantity FLOAT,
    last_fill_price FLOAT,
    last_fill_quantity FLOAT,
    remaining_quantity FLOAT,
    create_date DATETIME,
    transaction_date DATETIME,
    class VARCHAR(50),
    option_symbol VARCHAR(100),
    FOREIGN KEY (order_id) REFERENCES td_orders(id)
);
