 CREATE TABLE td_account_order (
    id BIGINT PRIMARY KEY,
    type VARCHAR(50),
    symbol VARCHAR(50),
    side VARCHAR(50),
    quantity DECIMAL(10, 2),
    status VARCHAR(50),
    duration VARCHAR(50),
    price DECIMAL(10, 2),
    avg_fill_price DECIMAL(10, 2),
    exec_quantity DECIMAL(10, 2),
    last_fill_price DECIMAL(10, 2),
    last_fill_quantity DECIMAL(10, 2),
    remaining_quantity DECIMAL(10, 2),
    create_date DATETIME,
    transaction_date DATETIME,
    class VARCHAR(50),
    strategy VARCHAR(50),
    reason_description TEXT
);
